### ISSUE TITLE
Crash on opening video

### ISSUE THREAD

**Issue by NobodyForNothing** [devhyper/open-video-editor#54]
#### Steps

1. open app
2. tab open video button
3. select video
4. the app crashes

#### Device info

Device: Xaiomi Mi 9, Android 10
App version: 1.1 Fdroid

#### Error log

```
java.lang.SecurityException: No persistable permission grants found for UID 10706 and Uri content://media/external/file/10500 [user 0]
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.app.IUriGrantsManager$Stub$Proxy.takePersistableUriPermission(IUriGrantsManager.java:280)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:2444)
	at c6.u.E(Unknown Source:435)
	at n.r0.b(Unknown Source:186)
	at n.r0.o(Unknown Source:15)
	at n0.c.o(Unknown Source:53)
	at m1.r1.a(Unknown Source:24)
	at p.l1.a(Unknown Source:244)
	at p.l1.o(Unknown Source:188)
	at n0.c.o(Unknown Source:53)
	at s3.u.b(Unknown Source:4)
	at b6.i.d(Unknown Source:147)
	at m1.s1.a(Unknown Source:284)
	at r.h.a(Unknown Source:58)
	at r.h.o(Unknown Source:15)
	at n0.c.o(Unknown Source:53)
	at s3.u.b(Unknown Source:4)
	at b6.i.d(Unknown Source:147)
	at m1.a1.a(Unknown Source:486)
	at m1.t3.a(Unknown Source:170)
	at m1.t3.o(Unknown Source:27)
	at n0.c.o(Unknown Source:53)
	at s3.u.b(Unknown Source:4)
	at b6.i.c(Unknown Source:215)
	at m1.t3.a(Unknown Source:144)
	at m1.t3.o(Unknown Source:15)
	at n0.c.o(Unknown Source:53)
	at b6.i.Y0(Unknown Source:14)
	at f0.r.r(Unknown Source:117)
	at f0.r.k(Unknown Source:10)
	at f0.y.n(Unknown Source:33)
	at f0.h2.a(Unknown Source:34)
	at f0.y.o(Unknown Source:8)
	at f0.y.d(Unknown Source:2)
	at m.u.c(Unknown Source:502)
	at m1.x.setOnViewTreeOwnersAvailable(Unknown Source:6)
	at m1.u3.d(Unknown Source:9)
	at m1.u3.c(Unknown Source:18)
	at androidx.lifecycle.u.a(Unknown Source:22)
	at androidx.lifecycle.v.c(Unknown Source:250)
	at m.u.c(Unknown Source:473)
	at m1.x.onAttachedToWindow(Unknown Source:102)
	at android.view.View.dispatchAttachedToWindow(View.java:19740)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3458)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2091)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1782)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7776)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.takePersistableUriPermission(UriGrantsManagerService.java:329)
	at android.app.IUriGrantsManager$Stub.onTransact(IUriGrantsManager.java:139)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```

**Comment by devhyper** [comment]
90948ae
